apiVersion: v1
kind: Service
metadata:
  name: lms-backend-cluster-svc 
  labels:
    app: cluster-ip-backend-label
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
