apiVersion: v1
kind: Service
metadata:
  name: lms-frontend-cluster-svc 
  labels:
    app: clusterip-frontend-label
spec:
  selector:
    app: frontend
  ports:
    - port: 8091
      targetPort: 8091
